module.exports = {
  happy: [
    "I'm glad to hear you're happy! How about some cheerful music?",
    "Feeling good? Let's make it even better with some upbeat tunes!",
    "Great! Here's something to match your positive vibe!",
    "Fantastic to hear! How about some music to keep that smile going?",
    "Feeling on top of the world? Let's amplify that with some great tracks!",
    "Awesome! Here's something that'll keep those good vibes rolling!",
    "Happy days! Let's add a little extra joy with this tune.",
    "You're radiating joy! Let's keep that going with some lively beats.",
    "Your happiness is contagious! Here's a song to celebrate.",
    "Sounds like a wonderful day! Let's make it even better with music.",
  ],
  sad: [
    "I'm sorry to hear that. How about a song to lift your spirits?",
    "Feeling down? Maybe some music can brighten your day.",
    "I hope this song helps you feel better!",
    "Tough times. This song might bring a little light to your day.",
    "It’s okay to feel low. Here’s a melody to help soothe you.",
    "Hang in there. This track might just be the comfort you need.",
    "Sorry you're feeling this way. Music has a way of healing, give this a try.",
    "Sending positive vibes your way. This song might help.",
    "Bad days happen. Here's a tune to help you through.",
    "Music is a great companion. Let this song be a friend to you.",
  ],
};
